version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - "gitlab_data:/var/opt/gitlab"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_config:/etc/gitlab"
    networks:
      - default
      - traefik-public
    configs:
      - source: gitlab.rb
        target: /etc/gitlab/gitlab.rb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Uses the environment variable DOMAIN
        - traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN?Variable not set}`)
        - traefik.http.routers.gitlab.entrypoints=https
        - traefik.http.routers.gitlab.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.gitlab.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        # - traefik.http.routers.gitlab.middlewares=admin-auth
        - traefik.http.services.gitlab.loadbalancer.server.port=443
        - traefik.http.services.gitlab.loadbalancer.server.scheme=https
  redis:
    image: "redis:alpine3.19"

  postgres:
    image: "postgres:alpine3.19"
    volumes:
      - "postgres_data:/data"
    environment:
      POSTGRES_USER: "gitlab"
      POSTGRES_PASSWORD: "gitlab"
      PGDATA: "/data"
      POSTGRES_DB:
        "gitlab"

        #  grafana:
        # image: grafana/grafana:latest
        #environment:
        #GF_PATHS_CONFIG: "/grafana.ini"
        #configs:
        #- grafana.ini
        #volumes:
        #- "grafana_data:/data"
        #networks:
        #- default
        #- traefik-public
        #deploy:
        #labels:
        #- traefik.enable=true
        #- traefik.docker.network=traefik-public
        #- traefik.constraint-label=traefik-public
        #- traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN?Variable not set}`)
        #- traefik.http.routers.grafana.entrypoints=https
        #- traefik.http.routers.grafana.tls=true
        #- traefik.http.routers.grafana.tls.certresolver=le
        #        - traefik.http.services.grafana.loadbalancer.server.port=3000
volumes:
  gitlab_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=127.0.0.1"
      device: ":/gitlab-swarm/gitlab/data"
  gitlab_logs:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=127.0.0.1"
      device: ":/gitlab-swarm/gitlab/logs"
  gitlab_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=127.0.0.1"
      device: ":/gitlab-swarm/gitlab/config"
  postgres_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=127.0.0.1"
      device: ":/gitlab-swarm/postgres"
  grafana_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=127.0.0.1"
      device: ":/gitlab-swarm/grafana"

configs:
  gitlab.rb:
    file: "./gitlab.rb"
  grafana.ini:
    file: "./grafana.ini"

networks:
  net:
    driver: overlay
  traefik-public:
    external: true
