version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      # - "gitlab_data:/var/opt/gitlab"
      # - "gitlab_logs:/var/log/gitlab"
      # - "gitlab_config:/etc/gitlab"
      - "./data:/var/opt/gitlab"
      - "./logs:/var/log/gitlab"
      - "./config:/etc/gitlab"
    networks:
      - net
      - proxy
    configs:
      - source: gitlab.rb
        target: /etc/gitlab/gitlab.rb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=proxy
        # Uses the environment variable DOMAIN
        - traefik.http.routers.gitlab.rule=Host(`gitlab.${DOMAIN?Variable not set}`)
        - traefik.http.routers.gitlab.entrypoints=https
        - traefik.http.routers.gitlab.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        # - traefik.http.routers.gitlab.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        # - traefik.http.routers.gitlab.middlewares=admin-auth
        # - traefik.http.services.gitlab.loadbalancer.server.port=443
        - traefik.http.services.gitlab.loadbalancer.server.scheme=https
        - traefik.http.routers.gitlab.entrypoints=websecure
        - traefik.http.routers.gitlab.service=gitlab
        - traefik.http.routers.gitlab.tls.certresolver=letsencryptresolver
        - traefik.http.services.gitlab.loadbalancer.server.port=80
  redis:
    image: "redis:alpine3.19"
    networks:
      - net

  postgresql:
    image: "postgres:alpine3.19"
    networks:
      - net
    volumes:
      - "postgres_data:/data"
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_USER: "gitlab"
      POSTGRES_PASSWORD: "gitlab"
      PGDATA: "/data"
      POSTGRES_DB: "gitlab"

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - net
      - proxy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL?Variable not set}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD?Variable not set}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=proxy
        # Uses the environment variable DOMAIN
        - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN?Variable not set}`)
        - traefik.http.routers.pgadmin.entrypoints=https
        - traefik.http.routers.pgadmin.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.pgadmin.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        # - traefik.http.routers.pgadmin.middlewares=admin-auth
        - traefik.http.services.pgadmin.loadbalancer.server.port=80
volumes:
  postgres_data:
    driver: local
  pgadmin-data:

configs:
  gitlab.rb:
    file: "gitlab.rb"

networks:
  proxy:
    external: true
  net:
    driver: overlay
